[project]
name = "balthazaar"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "flask==3.1.0",
    "flask-sqlalchemy==3.1.1",
    "python-dotenv==1.0.1",
    "gunicorn==23.0.0",
]

[tool.replit]
run = "python main.py"
